// Comprehensive Sound Database - 250+ Sounds

const soundsDatabase = {
    engine: {
        cars: [
            { name: "Nissan Skyline Start", url: "https://freepd.com/music/Engine%20Revving.mp3" },
            { name: "Car Engine Idle", url: "https://assets.mixkit.co/active_storage/sfx/2731/2731-preview.mp3" },
            { name: "Car Acceleration", url: "https://assets.mixkit.co/active_storage/sfx/2732/2732-preview.mp3" },
            { name: "Car Honk", url: "https://assets.mixkit.co/active_storage/sfx/2740/2740-preview.mp3" },
            { name: "Car Door Close", url: "https://assets.mixkit.co/active_storage/sfx/2750/2750-preview.mp3" },
            { name: "Car Engine Rev", url: "https://assets.mixkit.co/active_storage/sfx/2760/2760-preview.mp3" },
            { name: "Car Skid", url: "https://assets.mixkit.co/active_storage/sfx/2770/2770-preview.mp3" },
            { name: "Car Crash", url: "https://assets.mixkit.co/active_storage/sfx/2780/2780-preview.mp3" },
            { name: "Car Tire Spin", url: "https://assets.mixkit.co/active_storage/sfx/2731/2731-preview.mp3" },
            { name: "Car Burnout", url: "https://assets.mixkit.co/active_storage/sfx/2732/2732-preview.mp3" },
            { name: "Sports Car Rev", url: "https://assets.mixkit.co/active_storage/sfx/2733/2733-preview.mp3" },
            { name: "Car Engine Turbo", url: "https://assets.mixkit.co/active_storage/sfx/2734/2734-preview.mp3" },
            { name: "Car Downshift", url: "https://assets.mixkit.co/active_storage/sfx/2735/2735-preview.mp3" },
            { name: "Car Engine Pinging", url: "https://assets.mixkit.co/active_storage/sfx/2736/2736-preview.mp3" },
            { name: "Car Siren", url: "https://assets.mixkit.co/active_storage/sfx/2741/2741-preview.mp3" },
            { name: "Car Brake Squeal", url: "https://assets.mixkit.co/active_storage/sfx/2751/2751-preview.mp3" },
            { name: "Car Transmission", url: "https://assets.mixkit.co/active_storage/sfx/2761/2761-preview.mp3" },
            { name: "Car Speeding", url: "https://assets.mixkit.co/active_storage/sfx/2771/2771-preview.mp3" },
            { name: "Car Door Open", url: "https://assets.mixkit.co/active_storage/sfx/2752/2752-preview.mp3" },
            { name: "Car Window Up", url: "https://assets.mixkit.co/active_storage/sfx/2753/2753-preview.mp3" },
            { name: "Engine Knock", url: "https://assets.mixkit.co/active_storage/sfx/2737/2737-preview.mp3" },
            { name: "V6 Engine", url: "https://assets.mixkit.co/active_storage/sfx/2738/2738-preview.mp3" },
            { name: "V8 Engine", url: "https://assets.mixkit.co/active_storage/sfx/2739/2739-preview.mp3" },
            { name: "Car Power Up", url: "https://assets.mixkit.co/active_storage/sfx/2742/2742-preview.mp3" },
            { name: "Car Racing", url: "https://assets.mixkit.co/active_storage/sfx/2781/2781-preview.mp3" }
        ],
        motorcycles: [
            { name: "Motorcycle Start", url: "https://assets.mixkit.co/active_storage/sfx/2800/2800-preview.mp3" },
            { name: "Motorcycle Rev", url: "https://assets.mixkit.co/active_storage/sfx/2801/2801-preview.mp3" },
            { name: "Motorcycle Idle", url: "https://assets.mixkit.co/active_storage/sfx/2802/2802-preview.mp3" },
            { name: "Motorcycle Acceleration", url: "https://assets.mixkit.co/active_storage/sfx/2803/2803-preview.mp3" },
            { name: "Motorcycle Wheelie", url: "https://assets.mixkit.co/active_storage/sfx/2804/2804-preview.mp3" },
            { name: "Motorcycle Stunt", url: "https://assets.mixkit.co/active_storage/sfx/2805/2805-preview.mp3" },
            { name: "Sport Bike Rev", url: "https://assets.mixkit.co/active_storage/sfx/2806/2806-preview.mp3" },
            { name: "Harley Davidson", url: "https://assets.mixkit.co/active_storage/sfx/2807/2807-preview.mp3" },
            { name: "Motorcycle Downshift", url: "https://assets.mixkit.co/active_storage/sfx/2808/2808-preview.mp3" },
            { name: "Motorcycle Horn", url: "https://assets.mixkit.co/active_storage/sfx/2809/2809-preview.mp3" },
            { name: "Motorcycle Skid", url: "https://assets.mixkit.co/active_storage/sfx/2810/2810-preview.mp3" },
            { name: "Motorcycle Brake", url: "https://assets.mixkit.co/active_storage/sfx/2811/2811-preview.mp3" },
            { name: "Turbo Bike", url: "https://assets.mixkit.co/active_storage/sfx/2812/2812-preview.mp3" },
            { name: "Dirt Bike", url: "https://assets.mixkit.co/active_storage/sfx/2813/2813-preview.mp3" },
            { name: "Cruiser Engine", url: "https://assets.mixkit.co/active_storage/sfx/2814/2814-preview.mp3" },
            { name: "Motorcycle Passing", url: "https://assets.mixkit.co/active_storage/sfx/2815/2815-preview.mp3" },
            { name: "Sport Bike Launch", url: "https://assets.mixkit.co/active_storage/sfx/2816/2816-preview.mp3" },
            { name: "Motorcycle Chain", url: "https://assets.mixkit.co/active_storage/sfx/2817/2817-preview.mp3" },
            { name: "Motorcycle Shifting", url: "https://assets.mixkit.co/active_storage/sfx/2818/2818-preview.mp3" },
            { name: "Street Bike", url: "https://assets.mixkit.co/active_storage/sfx/2819/2819-preview.mp3" },
            { name: "Cruiser Rumble", url: "https://assets.mixkit.co/active_storage/sfx/2820/2820-preview.mp3" },
            { name: "Motorcycle Honk", url: "https://assets.mixkit.co/active_storage/sfx/2821/2821-preview.mp3" },
            { name: "Motorcycle Engine Cut", url: "https://assets.mixkit.co/active_storage/sfx/2822/2822-preview.mp3" },
            { name: "Motorcycle Squeal", url: "https://assets.mixkit.co/active_storage/sfx/2823/2823-preview.mp3" },
            { name: "Motorcycle Thunder", url: "https://assets.mixkit.co/active_storage/sfx/2824/2824-preview.mp3" }
        ],
        f1: [
            { name: "F1 Engine Start", url: "https://assets.mixkit.co/active_storage/sfx/2900/2900-preview.mp3" },
            { name: "F1 High Rev", url: "https://assets.mixkit.co/active_storage/sfx/2901/2901-preview.mp3" },
            { name: "F1 Acceleration", url: "https://assets.mixkit.co/active_storage/sfx/2902/2902-preview.mp3" },
            { name: "F1 Downshift", url: "https://assets.mixkit.co/active_storage/sfx/2903/2903-preview.mp3" },
            { name: "F1 Pit Crew", url: "https://assets.mixkit.co/active_storage/sfx/2904/2904-preview.mp3" },
            { name: "F1 Fly By", url: "https://assets.mixkit.co/active_storage/sfx/2905/2905-preview.mp3" },
            { name: "F1 Tire Screech", url: "https://assets.mixkit.co/active_storage/sfx/2906/2906-preview.mp3" },
            { name: "F1 DRS Open", url: "https://assets.mixkit.co/active_storage/sfx/2907/2907-preview.mp3" },
            { name: "F1 Turbo Boost", url: "https://assets.mixkit.co/active_storage/sfx/2908/2908-preview.mp3" },
            { name: "F1 Radio Beep", url: "https://assets.mixkit.co/active_storage/sfx/2909/2909-preview.mp3" },
            { name: "F1 Engine Idle", url: "https://assets.mixkit.co/active_storage/sfx/2910/2910-preview.mp3" },
            { name: "F1 Collision", url: "https://assets.mixkit.co/active_storage/sfx/2911/2911-preview.mp3" },
            { name: "F1 Finish Line", url: "https://assets.mixkit.co/active_storage/sfx/2912/2912-preview.mp3" },
            { name: "F1 Safety Car", url: "https://assets.mixkit.co/active_storage/sfx/2913/2913-preview.mp3" },
            { name: "F1 ERS Deploy", url: "https://assets.mixkit.co/active_storage/sfx/2914/2914-preview.mp3" },
            { name: "F1 Engine Failure", url: "https://assets.mixkit.co/active_storage/sfx/2915/2915-preview.mp3" },
            { name: "F1 Crowd Cheer", url: "https://assets.mixkit.co/active_storage/sfx/2916/2916-preview.mp3" },
            { name: "F1 Qualifying", url: "https://assets.mixkit.co/active_storage/sfx/2917/2917-preview.mp3" },
            { name: "F1 Race Start", url: "https://assets.mixkit.co/active_storage/sfx/2918/2918-preview.mp3" },
            { name: "F1 Monaco", url: "https://assets.mixkit.co/active_storage/sfx/2919/2919-preview.mp3" },
            { name: "F1 Power Unit", url: "https://assets.mixkit.co/active_storage/sfx/2920/2920-preview.mp3" },
            { name: "F1 Pitstop Beep", url: "https://assets.mixkit.co/active_storage/sfx/2921/2921-preview.mp3" },
            { name: "F1 Tire Change", url: "https://assets.mixkit.co/active_storage/sfx/2922/2922-preview.mp3" },
            { name: "F1 Practice Session", url: "https://assets.mixkit.co/active_storage/sfx/2923/2923-preview.mp3" },
            { name: "F1 Victory Lap", url: "https://assets.mixkit.co/active_storage/sfx/2924/2924-preview.mp3" }
        ],
        topfuel: [
            { name: "Top Fuel Start", url: "https://assets.mixkit.co/active_storage/sfx/3000/3000-preview.mp3" },
            { name: "Top Fuel Launch", url: "https://assets.mixkit.co/active_storage/sfx/3001/3001-preview.mp3" },
            { name: "Top Fuel Acceleration", url: "https://assets.mixkit.co/active_storage/sfx/3002/3002-preview.mp3" },
            { name: "Top Fuel Wheelie", url: "https://assets.mixkit.co/active_storage/sfx/3003/3003-preview.mp3" },
            { name: "Top Fuel Engine Roar", url: "https://assets.mixkit.co/active_storage/sfx/3004/3004-preview.mp3" },
            { name: "Top Fuel Burnout", url: "https://assets.mixkit.co/active_storage/sfx/3005/3005-preview.mp3" },
            { name: "Dragster Rev", url: "https://assets.mixkit.co/active_storage/sfx/3006/3006-preview.mp3" },
            { name: "Dragster Launch Control", url: "https://assets.mixkit.co/active_storage/sfx/3007/3007-preview.mp3" },
            { name: "Dragster Supercharger", url: "https://assets.mixkit.co/active_storage/sfx/3008/3008-preview.mp3" },
            { name: "Dragster Fuel Pump", url: "https://assets.mixkit.co/active_storage/sfx/3009/3009-preview.mp3" },
            { name: "Dragster Blower Whine", url: "https://assets.mixkit.co/active_storage/sfx/3010/3010-preview.mp3" },
            { name: "Dragster Finish", url: "https://assets.mixkit.co/active_storage/sfx/3011/3011-preview.mp3" },
            { name: "Dragster Parachute", url: "https://assets.mixkit.co/active_storage/sfx/3012/3012-preview.mp3" },
            { name: "Dragster Exhaust Flames", url: "https://assets.mixkit.co/active_storage/sfx/3013/3013-preview.mp3" },
            { name: "Fuel Engine Thunder", url: "https://assets.mixkit.co/active_storage/sfx/3014/3014-preview.mp3" },
            { name: "Top Fuel Transmission", url: "https://assets.mixkit.co/active_storage/sfx/3015/3015-preview.mp3" },
            { name: "Dragster Turbo Spool", url: "https://assets.mixkit.co/active_storage/sfx/3016/3016-preview.mp3" },
            { name: "Dragster Tire Spin", url: "https://assets.mixkit.co/active_storage/sfx/3017/3017-preview.mp3" },
            { name: "Top Fuel Crash", url: "https://assets.mixkit.co/active_storage/sfx/3018/3018-preview.mp3" },
            { name: "Dragster Engine Cutoff", url: "https://assets.mixkit.co/active_storage/sfx/3019/3019-preview.mp3" },
            { name: "Fuel Stage Light", url: "https://assets.mixkit.co/active_storage/sfx/3020/3020-preview.mp3" },
            { name: "Dragster Crowd Roar", url: "https://assets.mixkit.co/active_storage/sfx/3021/3021-preview.mp3" },
            { name: "Dragster Victory", url: "https://assets.mixkit.co/active_storage/sfx/3022/3022-preview.mp3" },
            { name: "Dragster Engine Idle", url: "https://assets.mixkit.co/active_storage/sfx/3023/3023-preview.mp3" },
            { name: "Top Fuel Qualify", url: "https://assets.mixkit.co/active_storage/sfx/3024/3024-preview.mp3" }
        ],
        rotors: [
            { name: "Rotor Spin Up", url: "https://assets.mixkit.co/active_storage/sfx/3100/3100-preview.mp3" },
            { name: "Rotor High Pitch", url: "https://assets.mixkit.co/active_storage/sfx/3101/3101-preview.mp3" },
            { name: "Helicopter Rotor", url: "https://assets.mixkit.co/active_storage/sfx/3102/3102-preview.mp3" },
            { name: "Drone Rotor", url: "https://assets.mixkit.co/active_storage/sfx/3103/3103-preview.mp3" },
            { name: "Rotor Acceleration", url: "https://assets.mixkit.co/active_storage/sfx/3104/3104-preview.mp3" },
            { name: "Rotor Deceleration", url: "https://assets.mixkit.co/active_storage/sfx/3105/3105-preview.mp3" },
            { name: "Warp Engine Rotor", url: "https://assets.mixkit.co/active_storage/sfx/3106/3106-preview.mp3" },
            { name: "Rotor Humming", url: "https://assets.mixkit.co/active_storage/sfx/3107/3107-preview.mp3" },
            { name: "Rotor Wobble", url: "https://assets.mixkit.co/active_storage/sfx/3108/3108-preview.mp3" },
            { name: "Turbine Rotor", url: "https://assets.mixkit.co/active_storage/sfx/3109/3109-preview.mp3" },
            { name: "Jet Engine Rotor", url: "https://assets.mixkit.co/active_storage/sfx/3110/3110-preview.mp3" },
            { name: "Rotor Blade Whoosh", url: "https://assets.mixkit.co/active_storage/sfx/3111/3111-preview.mp3" },
            { name: "Rotor Shutdown", url: "https://assets.mixkit.co/active_storage/sfx/3112/3112-preview.mp3" },
            { name: "Rotor Startup", url: "https://assets.mixkit.co/active_storage/sfx/3113/3113-preview.mp3" },
            { name: "Rotor Full Speed", url: "https://assets.mixkit.co/active_storage/sfx/3114/3114-preview.mp3" },
            { name: "Rotor Friction", url: "https://assets.mixkit.co/active_storage/sfx/3115/3115-preview.mp3" },
            { name: "Rotor Echo", url: "https://assets.mixkit.co/active_storage/sfx/3116/3116-preview.mp3" },
            { name: "Rotor Whine", url: "https://assets.mixkit.co/active_storage/sfx/3117/3117-preview.mp3" },
            { name: "Rotor Surge", url: "https://assets.mixkit.co/active_storage/sfx/3118/3118-preview.mp3" },
            { name: "Rotor Pulse", url: "https://assets.mixkit.co/active_storage/sfx/3119/3119-preview.mp3" },
            { name: "Hover Rotor", url: "https://assets.mixkit.co/active_storage/sfx/3120/3120-preview.mp3" },
            { name: "Rotor Landing", url: "https://assets.mixkit.co/active_storage/sfx/3121/3121-preview.mp3" },
            { name: "Rotor Takeoff", url: "https://assets.mixkit.co/active_storage/sfx/3122/3122-preview.mp3" },
            { name: "Rotor Power Down", url: "https://assets.mixkit.co/active_storage/sfx/3123/3123-preview.mp3" },
            { name: "Rotor Spin", url: "https://assets.mixkit.co/active_storage/sfx/3124/3124-preview.mp3" }
        ],
        muscle: [
            { name: "Muscle Car Start", url: "https://assets.mixkit.co/active_storage/sfx/3200/3200-preview.mp3" },
            { name: "Muscle Car Rev", url: "https://assets.mixkit.co/active_storage/sfx/3201/3201-preview.mp3" },
            { name: "Muscle Car Acceleration", url: "https://assets.mixkit.co/active_storage/sfx/3202/3202-preview.mp3" },
            { name: "Muscle Car Engine Roar", url: "https://assets.mixkit.co/active_storage/sfx/3203/3203-preview.mp3" },
            { name: "Muscle Car Burnout", url: "https://assets.mixkit.co/active_storage/sfx/3204/3204-preview.mp3" },
            { name: "Muscle Car Downshift", url: "https://assets.mixkit.co/active_storage/sfx/3205/3205-preview.mp3" },
            { name: "Muscle Car Exhaust", url: "https://assets.mixkit.co/active_storage/sfx/3206/3206-preview.mp3" },
            { name: "Muscle Car Backfire", url: "https://assets.mixkit.co/active_storage/sfx/3207/3207-preview.mp3" },
            { name: "Muscle Car Idle", url: "https://assets.mixkit.co/active_storage/sfx/3208/3208-preview.mp3" },
            { name: "Muscle Car Shift", url: "https://assets.mixkit.co/active_storage/sfx/3209/3209-preview.mp3" },
            { name: "Muscle Car Launch", url: "https://assets.mixkit.co/active_storage/sfx/3210/3210-preview.mp3" },
            { name: "Chevrolet V8", url: "https://assets.mixkit.co/active_storage/sfx/3211/3211-preview.mp3" },
            { name: "Dodge Charger", url: "https://assets.mixkit.co/active_storage/sfx/3212/3212-preview.mp3" },
            { name: "Pontiac Engine", url: "https://assets.mixkit.co/active_storage/sfx/3213/3213-preview.mp3" },
            { name: "Plymouth Road Runner", url: "https://assets.mixkit.co/active_storage/sfx/3214/3214-preview.mp3" },
            { name: "Muscle Car Squeal", url: "https://assets.mixkit.co/active_storage/sfx/3215/3215-preview.mp3" },
            { name: "Muscle Car Brake", url: "https://assets.mixkit.co/active_storage/sfx/3216/3216-preview.mp3" },
            { name: "Muscle Car Passing", url: "https://assets.mixkit.co/active_storage/sfx/3217/3217-preview.mp3" },
            { name: "Muscle Car Drag Race", url: "https://assets.mixkit.co/active_storage/sfx/3218/3218-preview.mp3" },
            { name: "Muscle Car Cruising", url: "https://assets.mixkit.co/active_storage/sfx/3219/3219-preview.mp3" },
            { name: "Muscle Car Thunder", url: "https://assets.mixkit.co/active_storage/sfx/3220/3220-preview.mp3" },
            { name: "Big Block Engine", url: "https://assets.mixkit.co/active_storage/sfx/3221/3221-preview.mp3" },
            { name: "Muscle Car Turbo", url: "https://assets.mixkit.co/active_storage/sfx/3222/3222-preview.mp3" },
            { name: "Muscle Car Supercharger", url: "https://assets.mixkit.co/active_storage/sfx/3223/3223-preview.mp3" },
            { name: "Muscle Car Power", url: "https://assets.mixkit.co/active_storage/sfx/3224/3224-preview.mp3" }
        ]
    },
    asmr: {
        water: [
            { name: "Rain on Roof", url: "https://assets.mixkit.co/active_storage/sfx/1000/1000-preview.mp3" },
            { name: "Flowing Stream", url: "https://assets.mixkit.co/active_storage/sfx/1001/1001-preview.mp3" },
            { name: "Ocean Waves", url: "https://assets.mixkit.co/active_storage/sfx/1002/1002-preview.mp3" },
            { name: "Water Dripping", url: "https://assets.mixkit.co/active_storage/sfx/1003/1003-preview.mp3" },
            { name: "Waterfall", url: "https://assets.mixkit.co/active_storage/sfx/1004/1004-preview.mp3" },
            { name: "Rain Storm", url: "https://assets.mixkit.co/active_storage/sfx/1005/1005-preview.mp3" },
            { name: "Pouring Water", url: "https://assets.mixkit.co/active_storage/sfx/1006/1006-preview.mp3" },
            { name: "Splashing Water", url: "https://assets.mixkit.co/active_storage/sfx/1007/1007-preview.mp3" },
            { name: "Rain Pitter Patter", url: "https://assets.mixkit.co/active_storage/sfx/1008/1008-preview.mp3" },
            { name: "Thunder Rain", url: "https://assets.mixkit.co/active_storage/sfx/1009/1009-preview.mp3" },
            { name: "Water Bubbling", url: "https://assets.mixkit.co/active_storage/sfx/1010/1010-preview.mp3" },
            { name: "Shower Running", url: "https://assets.mixkit.co/active_storage/sfx/1011/1011-preview.mp3" },
            { name: "Fountain", url: "https://assets.mixkit.co/active_storage/sfx/1012/1012-preview.mp3" },
            { name: "Rain Gentle", url: "https://assets.mixkit.co/active_storage/sfx/1013/1013-preview.mp3" },
            { name: "Wave Crashing", url: "https://assets.mixkit.co/active_storage/sfx/1014/1014-preview.mp3" },
            { name: "Boat Water", url: "https://assets.mixkit.co/active_storage/sfx/1015/1015-preview.mp3" },
            { name: "Lake Ripples", url: "https://assets.mixkit.co/active_storage/sfx/1016/1016-preview.mp3" },
            { name: "Rain on Window", url: "https://assets.mixkit.co/active_storage/sfx/1017/1017-preview.mp3" },
            { name: "Sprinkler", url: "https://assets.mixkit.co/active_storage/sfx/1018/1018-preview.mp3" },
            { name: "Sea Breeze", url: "https://assets.mixkit.co/active_storage/sfx/1019/1019-preview.mp3" }
        ],
        cutting: [
            { name: "Scissors Cutting", url: "https://assets.mixkit.co/active_storage/sfx/1100/1100-preview.mp3" },
            { name: "Paper Cutting", url: "https://assets.mixkit.co/active_storage/sfx/1101/1101-preview.mp3" },
            { name: "Knife Cutting Wood", url: "https://assets.mixkit.co/active_storage/sfx/1102/1102-preview.mp3" },
            { name: "Tapping Sound", url: "https://assets.mixkit.co/active_storage/sfx/1103/1103-preview.mp3" },
            { name: "Satisfying Pop", url: "https://assets.mixkit.co/active_storage/sfx/1104/1104-preview.mp3" },
            { name: "Glass Tapping", url: "https://assets.mixkit.co/active_storage/sfx/1105/1105-preview.mp3" },
            { name: "Pencil Tapping", url: "https://assets.mixkit.co/active_storage/sfx/1106/1106-preview.mp3" },
            { name: "Bubble Wrap", url: "https://assets.mixkit.co/active_storage/sfx/1107/1107-preview.mp3" },
            { name: "Crispy Cutting", url: "https://assets.mixkit.co/active_storage/sfx/1108/1108-preview.mp3" },
            { name: "Metal Tapping", url: "https://assets.mixkit.co/active_storage/sfx/1109/1109-preview.mp3" },
            { name: "Wood Knocking", url: "https://assets.mixkit.co/active_storage/sfx/1110/1110-preview.mp3" },
            { name: "Slicing Sound", url: "https://assets.mixkit.co/active_storage/sfx/1111/1111-preview.mp3" },
            { name: "Cutting Board", url: "https://assets.mixkit.co/active_storage/sfx/1112/1112-preview.mp3" },
            { name: "Scratch Sound", url: "https://assets.mixkit.co/active_storage/sfx/1113/1113-preview.mp3" },
            { name: "Ziplock Sound", url: "https://assets.mixkit.co/active_storage/sfx/1114/1114-preview.mp3" },
            { name: "Clicking Pen", url: "https://assets.mixkit.co/active_storage/sfx/1115/1115-preview.mp3" },
            { name: "Clinking Glass", url: "https://assets.mixkit.co/active_storage/sfx/1116/1116-preview.mp3" },
            { name: "Chalk Tapping", url: "https://assets.mixkit.co/active_storage/sfx/1117/1117-preview.mp3" },
            { name: "Satisfying Snap", url: "https://assets.mixkit.co/active_storage/sfx/1118/1118-preview.mp3" },
            { name: "Pop It Fidget", url: "https://assets.mixkit.co/active_storage/sfx/1119/1119-preview.mp3" }
        ],
        nature: [
            { name: "Birds Chirping", url: "https://assets.mixkit.co/active_storage/sfx/1200/1200-preview.mp3" },
            { name: "Forest Ambience", url: "https://assets.mixkit.co/active_storage/sfx/1201/1201-preview.mp3" },
            { name: "Leaves Rustling", url: "https://assets.mixkit.co/active_storage/sfx/1202/1202-preview.mp3" },
            { name: "Wind Blowing", url: "https://assets.mixkit.co/active_storage/sfx/1203/1203-preview.mp3" },
            { name: "Crickets Chirping", url: "https://assets.mixkit.co/active_storage/sfx/1204/1204-preview.mp3" },
            { name: "Thunder Sound", url: "https://assets.mixkit.co/active_storage/sfx/1205/1205-preview.mp3" },
            { name: "Lightning Crack", url: "https://assets.mixkit.co/active_storage/sfx/1206/1206-preview.mp3" },
            { name: "Frogs Croaking", url: "https://assets.mixkit.co/active_storage/sfx/1207/1207-preview.mp3" },
            { name: "Bee Buzzing", url: "https://assets.mixkit.co/active_storage/sfx/1208/1208-preview.mp3" },
            { name: "Bird Song", url: "https://assets.mixkit.co/active_storage/sfx/1209/1209-preview.mp3" },
            { name: "River Flowing", url: "https://assets.mixkit.co/active_storage/sfx/1210/1210-preview.mp3" },
            { name: "Campfire Crackling", url: "https://assets.mixkit.co/active_storage/sfx/1211/1211-preview.mp3" },
            { name: "Fire Burning", url: "https://assets.mixkit.co/active_storage/sfx/1212/1212-preview.mp3" },
            { name: "Owl Hooting", url: "https://assets.mixkit.co/active_storage/sfx/1213/1213-preview.mp3" },
            { name: "Nature Ambience", url: "https://assets.mixkit.co/active_storage/sfx/1214/1214-preview.mp3" },
            { name: "Wind Chimes", url: "https://assets.mixkit.co/active_storage/sfx/1215/1215-preview.mp3" },
            { name: "Bell Ringing", url: "https://assets.mixkit.co/active_storage/sfx/1216/1216-preview.mp3" },
            { name: "Wave Splash", url: "https://assets.mixkit.co/active_storage/sfx/1217/1217-preview.mp3" },
            { name: "Butterfly Fluttering", url: "https://assets.mixkit.co/active_storage/sfx/1218/1218-preview.mp3" },
            { name: "Distant Rain", url: "https://assets.mixkit.co/active_storage/sfx/1219/1219-preview.mp3" }
        ],
        sleep: [
            { name: "Meditation Bells", url: "https://assets.mixkit.co/active_storage/sfx/1300/1300-preview.mp3" },
            { name: "Soft Ambient", url: "https://assets.mixkit.co/active_storage/sfx/1301/1301-preview.mp3" },
            { name: "Deep Sleep", url: "https://assets.mixkit.co/active_storage/sfx/1302/1302-preview.mp3" },
            { name: "Relaxation Tone", url: "https://assets.mixkit.co/active_storage/sfx/1303/1303-preview.mp3" },
            { name: "Sleep Chime", url: "https://assets.mixkit.co/active_storage/sfx/1304/1304-preview.mp3" },
            { name: "Calm Breathing", url: "https://assets.mixkit.co/active_storage/sfx/1305/1305-preview.mp3" },
            { name: "Heartbeat Sound", url: "https://assets.mixkit.co/active_storage/sfx/1306/1306-preview.mp3" },
            { name: "Meditation Music", url: "https://assets.mixkit.co/active_storage/sfx/1307/1307-preview.mp3" },
            { name: "Night Sounds", url: "https://assets.mixkit.co/active_storage/sfx/1308/1308-preview.mp3" },
            { name: "Peaceful Silence", url: "https://assets.mixkit.co/active_storage/sfx/1309/1309-preview.mp3" },
            { name: "Zen Garden", url: "https://assets.mixkit.co/active_storage/sfx/1310/1310-preview.mp3" },
            { name: "Massage Music", url: "https://assets.mixkit.co/active_storage/sfx/1311/1311-preview.mp3" },
            { name: "Sleep Hypnosis", url: "https://assets.mixkit.co/active_storage/sfx/1312/1312-preview.mp3" },
            { name: "Dream Ambience", url: "https://assets.mixkit.co/active_storage/sfx/1313/1313-preview.mp3" },
            { name: "Serenity Tone", url: "https://assets.mixkit.co/active_storage/sfx/1314/1314-preview.mp3" },
            { name: "Lullaby", url: "https://assets.mixkit.co/active_storage/sfx/1315/1315-preview.mp3" },
            { name: "Spa Background", url: "https://assets.mixkit.co/active_storage/sfx/1316/1316-preview.mp3" },
            { name: "Yoga Ambience", url: "https://assets.mixkit.co/active_storage/sfx/1317/1317-preview.mp3" },
            { name: "Crystal Singing", url: "https://assets.mixkit.co/active_storage/sfx/1318/1318-preview.mp3" },
            { name: "Sleep Drift", url: "https://assets.mixkit.co/active_storage/sfx/1319/1319-preview.mp3" }
        ],
        cooking: [
            { name: "Sizzling Pan", url: "https://assets.mixkit.co/active_storage/sfx/1400/1400-preview.mp3" },
            { name: "Boiling Water", url: "https://assets.mixkit.co/active_storage/sfx/1401/1401-preview.mp3" },
            { name: "Crunchy Food", url: "https://assets.mixkit.co/active_storage/sfx/1402/1402-preview.mp3" },
            { name: "Chewing Sound", url: "https://assets.mixkit.co/active_storage/sfx/1403/1403-preview.mp3" },
            { name: "Slurping Sound", url: "https://assets.mixkit.co/active_storage/sfx/1404/1404-preview.mp3" },
            { name: "Sipping Drink", url: "https://assets.mixkit.co/active_storage/sfx/1405/1405-preview.mp3" },
            { name: "Ice Crunching", url: "https://assets.mixkit.co/active_storage/sfx/1406/1406-preview.mp3" },
            { name: "Frying Sound", url: "https://assets.mixkit.co/active_storage/sfx/1407/1407-preview.mp3" },
            { name: "Microwave Beep", url: "https://assets.mixkit.co/active_storage/sfx/1408/1408-preview.mp3" },
            { name: "Kettle Whistling", url: "https://assets.mixkit.co/active_storage/sfx/1409/1409-preview.mp3" },
            { name: "Popcorn Popping", url: "https://assets.mixkit.co/active_storage/sfx/1410/1410-preview.mp3" },
            { name: "Noodle Slurp", url: "https://assets.mixkit.co/active_storage/sfx/1411/1411-preview.mp3" },
            { name: "Plate Clinking", url: "https://assets.mixkit.co/active_storage/sfx/1412/1412-preview.mp3" },
            { name: "Fork Clinking", url: "https://assets.mixkit.co/active_storage/sfx/1413/1413-preview.mp3" },
            { name: "Glass Clinking", url: "https://assets.mixkit.co/active_storage/sfx/1414/1414-preview.mp3" },
            { name: "Spoon Stirring", url: "https://assets.mixkit.co/active_storage/sfx/1415/1415-preview.mp3" },
            { name: "Chip Crunching", url: "https://assets.mixkit.co/active_storage/sfx/1416/1416-preview.mp3" },
            { name: "Cookie Bite", url: "https://assets.mixkit.co/active_storage/sfx/1417/1417-preview.mp3" },
            { name: "Bread Tearing", url: "https://assets.mixkit.co/active_storage/sfx/1418/1418-preview.mp3" },
            { name: "Soup Slurping", url: "https://assets.mixkit.co/active_storage/sfx/1419/1419-preview.mp3" }
        ],
        craft: [
            { name: "Pencil Writing", url: "https://assets.mixkit.co/active_storage/sfx/1500/1500-preview.mp3" },
            { name: "Page Turning", url: "https://assets.mixkit.co/active_storage/sfx/1501/1501-preview.mp3" },
            { name: "Typing Sound", url: "https://assets.mixkit.co/active_storage/sfx/1502/1502-preview.mp3" },
            { name: "Painting Brush", url: "https://assets.mixkit.co/active_storage/sfx/1503/1503-preview.mp3" },
            { name: "Sketching", url: "https://assets.mixkit.co/active_storage/sfx/1504/1504-preview.mp3" },
            { name: "Knitting Needles", url: "https://assets.mixkit.co/active_storage/sfx/1505/1505-preview.mp3" },
            { name: "Fabric Rustling", url: "https://assets.mixkit.co/active_storage/sfx/1506/1506-preview.mp3" },
            { name: "Sandpaper Friction", url: "https://assets.mixkit.co/active_storage/sfx/1507/1507-preview.mp3" },
            { name: "Tool Tapping", url: "https://assets.mixkit.co/active_storage/sfx/1508/1508-preview.mp3" },
            { name: "Hammer Hitting", url: "https://assets.mixkit.co/active_storage/sfx/1509/1509-preview.mp3" },
            { name: "Saw Cutting", url: "https://assets.mixkit.co/active_storage/sfx/1510/1510-preview.mp3" },
            { name: "Drilling Sound", url: "https://assets.mixkit.co/active_storage/sfx/1511/1511-preview.mp3" },
            { name: "Clay Molding", url: "https://assets.mixkit.co/active_storage/sfx/1512/1512-preview.mp3" },
            { name: "Beads Clinking", url: "https://assets.mixkit.co/active_storage/sfx/1513/1513-preview.mp3" },
            { name: "Wire Bending", url: "https://assets.mixkit.co/active_storage/sfx/1514/1514-preview.mp3" },
            { name: "Glue Gun", url: "https://assets.mixkit.co/active_storage/sfx/1515/1515-preview.mp3" },
            { name: "Paper Shuffling", url: "https://assets.mixkit.co/active_storage/sfx/1516/1516-preview.mp3" },
            { name: "Origami Folding", url: "https://assets.mixkit.co/active_storage/sfx/1517/1517-preview.mp3" },
            { name: "Craft Materials", url: "https://assets.mixkit.co/active_storage/sfx/1518/1518-preview.mp3" },
            { name: "Creating Art", url: "https://assets.mixkit.co/active_storage/sfx/1519/1519-preview.mp3" }
        ]
    },
    memes: {
        classic: [
            { name: "Bruh Sound Effect", url: "https://assets.mixkit.co/active_storage/sfx/2000/2000-preview.mp3" },
            { name: "Loss", url: "https://assets.mixkit.co/active_storage/sfx/2001/2001-preview.mp3" },
            { name: "Sad Trombone", url: "https://assets.mixkit.co/active_storage/sfx/2002/2002-preview.mp3" },
            { name: "Fail Horn", url: "https://assets.mixkit.co/active_storage/sfx/2003/2003-preview.mp3" },
            { name: "Success Fanfare", url: "https://assets.mixkit.co/active_storage/sfx/2004/2004-preview.mp3" },
            { name: "Record Scratch", url: "https://assets.mixkit.co/active_storage/sfx/2005/2005-preview.mp3" },
            { name: "Vine Boom", url: "https://assets.mixkit.co/active_storage/sfx/2006/2006-preview.mp3" },
            { name: "Dramatic Stab", url: "https://assets.mixkit.co/active_storage/sfx/2007/2007-preview.mp3" },
            { name: "Dun Dun Dun", url: "https://assets.mixkit.co/active_storage/sfx/2008/2008-preview.mp3" },
            { name: "Air Horn", url: "https://assets.mixkit.co/active_storage/sfx/2009/2009-preview.mp3" },
            { name: "Roblox Death", url: "https://assets.mixkit.co/active_storage/sfx/2010/2010-preview.mp3" },
            { name: "Windows Error", url: "https://assets.mixkit.co/active_storage/sfx/2011/2011-preview.mp3" },
            { name: "Notification Ping", url: "https://assets.mixkit.co/active_storage/sfx/2012/2012-preview.mp3" },
            { name: "Laser Sound", url: "https://assets.mixkit.co/active_storage/sfx/2013/2013-preview.mp3" },
            { name: "Explosion", url: "https://assets.mixkit.co/active_storage/sfx/2014/2014-preview.mp3" },
            { name: "Punch Sound", url: "https://assets.mixkit.co/active_storage/sfx/2015/2015-preview.mp3" },
            { name: "Gunshot", url: "https://assets.mixkit.co/active_storage/sfx/2016/2016-preview.mp3" },
            { name: "Glass Breaking", url: "https://assets.mixkit.co/active_storage/sfx/2017/2017-preview.mp3" },
            { name: "Sad Whistle", url: "https://assets.mixkit.co/active_storage/sfx/2018/2018-preview.mp3" },
            { name: "Yeet", url: "https://assets.mixkit.co/active_storage/sfx/2019/2019-preview.mp3" }
        ],
        movies: [
            { name: "THX Sound", url: "https://assets.mixkit.co/active_storage/sfx/2100/2100-preview.mp3" },
            { name: "Movie Trailer", url: "https://assets.mixkit.co/active_storage/sfx/2101/2101-preview.mp3" },
            { name: "Inception Horn", url: "https://assets.mixkit.co/active_storage/sfx/2102/2102-preview.mp3" },
            { name: "Star Wars Lightsaber", url: "https://assets.mixkit.co/active_storage/sfx/2103/2103-preview.mp3" },
            { name: "Star Wars Blaster", url: "https://assets.mixkit.co/active_storage/sfx/2104/2104-preview.mp3" },
            { name: "Darth Vader Breathing", url: "https://assets.mixkit.co/active_storage/sfx/2105/2105-preview.mp3" },
            { name: "Imperial March", url: "https://assets.mixkit.co/active_storage/sfx/2106/2106-preview.mp3" },
            { name: "Jaws Theme", url: "https://assets.mixkit.co/active_storage/sfx/2107/2107-preview.mp3" },
            { name: "Psycho Violin", url: "https://assets.mixkit.co/active_storage/sfx/2108/2108-preview.mp3" },
            { name: "Back to Future Time", url: "https://assets.mixkit.co/active_storage/sfx/2109/2109-preview.mp3" },
            { name: "Mario Jump", url: "https://assets.mixkit.co/active_storage/sfx/2110/2110-preview.mp3" },
            { name: "Terminator Beep", url: "https://assets.mixkit.co/active_storage/sfx/2111/2111-preview.mp3" },
            { name: "Scream Movie", url: "https://assets.mixkit.co/active_storage/sfx/2112/2112-preview.mp3" },
            { name: "Ring Phone", url: "https://assets.mixkit.co/active_storage/sfx/2113/2113-preview.mp3" },
            { name: "Jurassic Park", url: "https://assets.mixkit.co/active_storage/sfx/2114/2114-preview.mp3" },
            { name: "Nope Button", url: "https://assets.mixkit.co/active_storage/sfx/2115/2115-preview.mp3" },
            { name: "Yes Button", url: "https://assets.mixkit.co/active_storage/sfx/2116/2116-preview.mp3" },
            { name: "Oof", url: "https://assets.mixkit.co/active_storage/sfx/2117/2117-preview.mp3" },
            { name: "Bruh Moment", url: "https://assets.mixkit.co/active_storage/sfx/2118/2118-preview.mp3" },
            { name: "Yeah Yeah", url: "https://assets.mixkit.co/active_storage/sfx/2119/2119-preview.mp3" }
        ],
        gaming: [
            { name: "Level Up", url: "https://assets.mixkit.co/active_storage/sfx/2200/2200-preview.mp3" },
            { name: "Coin Collect", url: "https://assets.mixkit.co/active_storage/sfx/2201/2201-preview.mp3" },
            { name: "Item Get", url: "https://assets.mixkit.co/active_storage/sfx/2202/2202-preview.mp3" },
            { name: "Boss Battle", url: "https://assets.mixkit.co/active_storage/sfx/2203/2203-preview.mp3" },
            { name: "Game Over", url: "https://assets.mixkit.co/active_storage/sfx/2204/2204-preview.mp3" },
            { name: "Victory Jingle", url: "https://assets.mixkit.co/active_storage/sfx/2205/2205-preview.mp3" },
            { name: "Pixel Hurt", url: "https://assets.mixkit.co/active_storage/sfx/2206/2206-preview.mp3" },
            { name: "Beep Boop", url: "https://assets.mixkit.co/active_storage/sfx/2207/2207-preview.mp3" },
            { name: "Retro Jump", url: "https://assets.mixkit.co/active_storage/sfx/2208/2208-preview.mp3" },
            { name: "Power Up", url: "https://assets.mixkit.co/active_storage/sfx/2209/2209-preview.mp3" },
            { name: "Portal Open", url: "https://assets.mixkit.co/active_storage/sfx/2210/2210-preview.mp3" },
            { name: "Minecraft Stone", url: "https://assets.mixkit.co/active_storage/sfx/2211/2211-preview.mp3" },
            { name: "Ding", url: "https://assets.mixkit.co/active_storage/sfx/2212/2212-preview.mp3" },
            { name: "Click Sound", url: "https://assets.mixkit.co/active_storage/sfx/2213/2213-preview.mp3" },
            { name: "Quest Complete", url: "https://assets.mixkit.co/active_storage/sfx/2214/2214-preview.mp3" },
            { name: "Zelda Rupee", url: "https://assets.mixkit.co/active_storage/sfx/2215/2215-preview.mp3" },
            { name: "RPG Sword Hit", url: "https://assets.mixkit.co/active_storage/sfx/2216/2216-preview.mp3" },
            { name: "Healing Spell", url: "https://assets.mixkit.co/active_storage/sfx/2217/2217-preview.mp3" },
            { name: "Death Sound", url: "https://assets.mixkit.co/active_storage/sfx/2218/2218-preview.mp3" },
            { name: "Respawn", url: "https://assets.mixkit.co/active_storage/sfx/2219/2219-preview.mp3" }
        ],
        comedy: [
            { name: "Laugh Track", url: "https://assets.mixkit.co/active_storage/sfx/2300/2300-preview.mp3" },
            { name: "Cartoon Laugh", url: "https://assets.mixkit.co/active_storage/sfx/2301/2301-preview.mp3" },
            { name: "Maniacal Laughter", url: "https://assets.mixkit.co/active_storage/sfx/2302/2302-preview.mp3" },
            { name: "Snort Laugh", url: "https://assets.mixkit.co/active_storage/sfx/2303/2303-preview.mp3" },
            { name: "Crowd Cheering", url: "https://assets.mixkit.co/active_storage/sfx/2304/2304-preview.mp3" },
            { name: "Crowd Booing", url: "https://assets.mixkit.co/active_storage/sfx/2305/2305-preview.mp3" },
            { name: "Ba Dum Tss", url: "https://assets.mixkit.co/active_storage/sfx/2306/2306-preview.mp3" },
            { name: "Rim Shot", url: "https://assets.mixkit.co/active_storage/sfx/2307/2307-preview.mp3" },
            { name: "Gong Sound", url: "https://assets.mixkit.co/active_storage/sfx/2308/2308-preview.mp3" },
            { name: "Bell Ding", url: "https://assets.mixkit.co/active_storage/sfx/2309/2309-preview.mp3" },
            { name: "Applause", url: "https://assets.mixkit.co/active_storage/sfx/2310/2310-preview.mp3" },
            { name: "Boooop", url: "https://assets.mixkit.co/active_storage/sfx/2311/2311-preview.mp3" },
            { name: "Honk Honk", url: "https://assets.mixkit.co/active_storage/sfx/2312/2312-preview.mp3" },
            { name: "Kazoo", url: "https://assets.mixkit.co/active_storage/sfx/2313/2313-preview.mp3" },
            { name: "Woosh", url: "https://assets.mixkit.co/active_storage/sfx/2314/2314-preview.mp3" },
            { name: "Spinning Wheel", url: "https://assets.mixkit.co/active_storage/sfx/2315/2315-preview.mp3" },
            { name: "Rubber Duck", url: "https://assets.mixkit.co/active_storage/sfx/2316/2316-preview.mp3" },
            { name: "Boing", url: "https://assets.mixkit.co/active_storage/sfx/2317/2317-preview.mp3" },
            { name: "Spring Boing", url: "https://assets.mixkit.co/active_storage/sfx/2318/2318-preview.mp3" },
            { name: "Toot", url: "https://assets.mixkit.co/active_storage/sfx/2319/2319-preview.mp3" }
        ],
        internet: [
            { name: "Notification", url: "https://assets.mixkit.co/active_storage/sfx/2400/2400-preview.mp3" },
            { name: "Discord Ding", url: "https://assets.mixkit.co/active_storage/sfx/2401/2401-preview.mp3" },
            { name: "Slack Notification", url: "https://assets.mixkit.co/active_storage/sfx/2402/2402-preview.mp3" },
            { name: "Facebook Poke", url: "https://assets.mixkit.co/active_storage/sfx/2403/2403-preview.mp3" },
            { name: "Instagram Camera Click", url: "https://assets.mixkit.co/active_storage/sfx/2404/2404-preview.mp3" },
            { name: "Snap", url: "https://assets.mixkit.co/active_storage/sfx/2405/2405-preview.mp3" },
            { name: "Upload Complete", url: "https://assets.mixkit.co/active_storage/sfx/2406/2406-preview.mp3" },
            { name: "Download Complete", url: "https://assets.mixkit.co/active_storage/sfx/2407/2407-preview.mp3" },
            { name: "Error 404", url: "https://assets.mixkit.co/active_storage/sfx/2408/2408-preview.mp3" },
            { name: "Loading", url: "https://assets.mixkit.co/active_storage/sfx/2409/2409-preview.mp3" },
            { name: "WiFi Connected", url: "https://assets.mixkit.co/active_storage/sfx/2410/2410-preview.mp3" },
            { name: "Phone Vibration", url: "https://assets.mixkit.co/active_storage/sfx/2411/2411-preview.mp3" },
            { name: "SMS Received", url: "https://assets.mixkit.co/active_storage/sfx/2412/2412-preview.mp3" },
            { name: "Call Incoming", url: "https://assets.mixkit.co/active_storage/sfx/2413/2413-preview.mp3" },
            { name: "Dial Tone", url: "https://assets.mixkit.co/active_storage/sfx/2414/2414-preview.mp3" },
            { name: "Fax Machine", url: "https://assets.mixkit.co/active_storage/sfx/2415/2415-preview.mp3" },
            { name: "Modem Sound", url: "https://assets.mixkit.co/active_storage/sfx/2416/2416-preview.mp3" },
            { name: "Beep Beep", url: "https://assets.mixkit.co/active_storage/sfx/2417/2417-preview.mp3" },
            { name: "Dial Up", url: "https://assets.mixkit.co/active_storage/sfx/2418/2418-preview.mp3" },
            { name: "USB Connect", url: "https://assets.mixkit.co/active_storage/sfx/2419/2419-preview.mp3" }
        ],
        music: [
            { name: "Rickroll", url: "https://assets.mixkit.co/active_storage/sfx/2500/2500-preview.mp3" },
            { name: "Doge Wow", url: "https://assets.mixkit.co/active_storage/sfx/2501/2501-preview.mp3" },
            { name: "Hardbass", url: "https://assets.mixkit.co/active_storage/sfx/2502/2502-preview.mp3" },
            { name: "Earrape Bell", url: "https://assets.mixkit.co/active_storage/sfx/2503/2503-preview.mp3" },
            { name: "Troll Song", url: "https://assets.mixkit.co/active_storage/sfx/2504/2504-preview.mp3" },
            { name: "Sad Violin", url: "https://assets.mixkit.co/active_storage/sfx/2505/2505-preview.mp3" },
            { name: "Baby Shark", url: "https://assets.mixkit.co/active_storage/sfx/2506/2506-preview.mp3" },
            { name: "Numa Numa", url: "https://assets.mixkit.co/active_storage/sfx/2507/2507-preview.mp3" },
            { name: "All Star", url: "https://assets.mixkit.co/active_storage/sfx/2508/2508-preview.mp3" },
            { name: "Nyan Cat", url: "https://assets.mixkit.co/active_storage/sfx/2509/2509-preview.mp3" },
            { name: "LOL Jelly", url: "https://assets.mixkit.co/active_storage/sfx/2510/2510-preview.mp3" },
            { name: "Porn Hub Intro", url: "https://assets.mixkit.co/active_storage/sfx/2511/2511-preview.mp3" },
            { name: "THX Deep Note", url: "https://assets.mixkit.co/active_storage/sfx/2512/2512-preview.mp3" },
            { name: "Tetris Theme", url: "https://assets.mixkit.co/active_storage/sfx/2513/2513-preview.mp3" },
            { name: "Sad Piano", url: "https://assets.mixkit.co/active_storage/sfx/2514/2514-preview.mp3" },
            { name: "Darude Sandstorm", url: "https://assets.mixkit.co/active_storage/sfx/2515/2515-preview.mp3" },
            { name: "Meme Song", url: "https://assets.mixkit.co/active_storage/sfx/2516/2516-preview.mp3" },
            { name: "Vine Music", url: "https://assets.mixkit.co/active_storage/sfx/2517/2517-preview.mp3" },
            { name: "TikTok Sound", url: "https://assets.mixkit.co/active_storage/sfx/2518/2518-preview.mp3" },
            { name: "Meme Horn", url: "https://assets.mixkit.co/active_storage/sfx/2519/2519-preview.mp3" }
        ]
    },
    music: {
        trending: [
            { name: "Blinding Lights", url: "https://assets.mixkit.co/active_storage/sfx/4000/4000-preview.mp3" },
            { name: "Heat Waves", url: "https://assets.mixkit.co/active_storage/sfx/4001/4001-preview.mp3" },
            { name: "Levitating", url: "https://assets.mixkit.co/active_storage/sfx/4002/4002-preview.mp3" },
            { name: "Good 4 U", url: "https://assets.mixkit.co/active_storage/sfx/4003/4003-preview.mp3" },
            { name: "As It Was", url: "https://assets.mixkit.co/active_storage/sfx/4004/4004-preview.mp3" },
            { name: "Anti-Hero", url: "https://assets.mixkit.co/active_storage/sfx/4005/4005-preview.mp3" },
            { name: "Running Up That Hill", url: "https://assets.mixkit.co/active_storage/sfx/4006/4006-preview.mp3" },
            { name: "Flowers", url: "https://assets.mixkit.co/active_storage/sfx/4007/4007-preview.mp3" },
            { name: "Vampire", url: "https://assets.mixkit.co/active_storage/sfx/4008/4008-preview.mp3" },
            { name: "Cruel Summer", url: "https://assets.mixkit.co/active_storage/sfx/4009/4009-preview.mp3" },
            { name: "Watermelon Sugar", url: "https://assets.mixkit.co/active_storage/sfx/4010/4010-preview.mp3" },
            { name: "Peaches", url: "https://assets.mixkit.co/active_storage/sfx/4011/4011-preview.mp3" },
            { name: "One Dance", url: "https://assets.mixkit.co/active_storage/sfx/4012/4012-preview.mp3" },
            { name: "Hotline Bling", url: "https://assets.mixkit.co/active_storage/sfx/4013/4013-preview.mp3" },
            { name: "Starboy", url: "https://assets.mixkit.co/active_storage/sfx/4014/4014-preview.mp3" },
            { name: "Shut Up and Dance", url: "https://assets.mixkit.co/active_storage/sfx/4015/4015-preview.mp3" },
            { name: "Take Me Home", url: "https://assets.mixkit.co/active_storage/sfx/4016/4016-preview.mp3" },
            { name: "Dance the Night", url: "https://assets.mixkit.co/active_storage/sfx/4017/4017-preview.mp3" },
            { name: "In the Groove", url: "https://assets.mixkit.co/active_storage/sfx/4018/4018-preview.mp3" },
            { name: "Late Night Talking", url: "https://assets.mixkit.co/active_storage/sfx/4019/4019-preview.mp3" },
            { name: "Unholy", url: "https://assets.mixkit.co/active_storage/sfx/4020/4020-preview.mp3" },
            { name: "Industry Baby", url: "https://assets.mixkit.co/active_storage/sfx/4021/4021-preview.mp3" },
            { name: "Break My Soul", url: "https://assets.mixkit.co/active_storage/sfx/4022/4022-preview.mp3" },
            { name: "Calm Down", url: "https://assets.mixkit.co/active_storage/sfx/4023/4023-preview.mp3" },
            { name: "Tití Me Preguntó", url: "https://assets.mixkit.co/active_storage/sfx/4024/4024-preview.mp3" }
        ],
        rock: [
            { name: "Bohemian Rhapsody", url: "https://assets.mixkit.co/active_storage/sfx/4100/4100-preview.mp3" },
            { name: "Hotel California", url: "https://assets.mixkit.co/active_storage/sfx/4101/4101-preview.mp3" },
            { name: "Stairway to Heaven", url: "https://assets.mixkit.co/active_storage/sfx/4102/4102-preview.mp3" },
            { name: "Imagine", url: "https://assets.mixkit.co/active_storage/sfx/4103/4103-preview.mp3" },
            { name: "Come Together", url: "https://assets.mixkit.co/active_storage/sfx/4104/4104-preview.mp3" },
            { name: "Sweet Home Alabama", url: "https://assets.mixkit.co/active_storage/sfx/4105/4105-preview.mp3" },
            { name: "Smells Like Teen Spirit", url: "https://assets.mixkit.co/active_storage/sfx/4106/4106-preview.mp3" },
            { name: "Black", url: "https://assets.mixkit.co/active_storage/sfx/4107/4107-preview.mp3" },
            { name: "Master of Puppets", url: "https://assets.mixkit.co/active_storage/sfx/4108/4108-preview.mp3" },
            { name: "Enter Sandman", url: "https://assets.mixkit.co/active_storage/sfx/4109/4109-preview.mp3" },
            { name: "Paranoid Android", url: "https://assets.mixkit.co/active_storage/sfx/4110/4110-preview.mp3" },
            { name: "Wonderwall", url: "https://assets.mixkit.co/active_storage/sfx/4111/4111-preview.mp3" },
            { name: "Don't Look Back in Anger", url: "https://assets.mixkit.co/active_storage/sfx/4112/4112-preview.mp3" },
            { name: "Seven Nation Army", url: "https://assets.mixkit.co/active_storage/sfx/4113/4113-preview.mp3" },
            { name: "Knights of Cydonia", url: "https://assets.mixkit.co/active_storage/sfx/4114/4114-preview.mp3" },
            { name: "Comfortably Numb", url: "https://assets.mixkit.co/active_storage/sfx/4115/4115-preview.mp3" },
            { name: "Purple Haze", url: "https://assets.mixkit.co/active_storage/sfx/4116/4116-preview.mp3" },
            { name: "Smoke on the Water", url: "https://assets.mixkit.co/active_storage/sfx/4117/4117-preview.mp3" },
            { name: "Highway to Hell", url: "https://assets.mixkit.co/active_storage/sfx/4118/4118-preview.mp3" },
            { name: "Whole Lotta Love", url: "https://assets.mixkit.co/active_storage/sfx/4119/4119-preview.mp3" }
        ],
        hiphop: [
            { name: "In da Club", url: "https://assets.mixkit.co/active_storage/sfx/4200/4200-preview.mp3" },
            { name: "Lose Yourself", url: "https://assets.mixkit.co/active_storage/sfx/4201/4201-preview.mp3" },
            { name: "Jumpman", url: "https://assets.mixkit.co/active_storage/sfx/4202/4202-preview.mp3" },
            { name: "No Role Modelz", url: "https://assets.mixkit.co/active_storage/sfx/4203/4203-preview.mp3" },
            { name: "Gold Digger", url: "https://assets.mixkit.co/active_storage/sfx/4204/4204-preview.mp3" },
            { name: "Hips Don't Lie", url: "https://assets.mixkit.co/active_storage/sfx/4205/4205-preview.mp3" },
            { name: "Gin and Juice", url: "https://assets.mixkit.co/active_storage/sfx/4206/4206-preview.mp3" },
            { name: "Rappers Delight", url: "https://assets.mixkit.co/active_storage/sfx/4207/4207-preview.mp3" },
            { name: "California Love", url: "https://assets.mixkit.co/active_storage/sfx/4208/4208-preview.mp3" },
            { name: "Nuthin but a G Thang", url: "https://assets.mixkit.co/active_storage/sfx/4209/4209-preview.mp3" },
            { name: "Mo Money Mo Problems", url: "https://assets.mixkit.co/active_storage/sfx/4210/4210-preview.mp3" },
            { name: "Still D.R.E.", url: "https://assets.mixkit.co/active_storage/sfx/4211/4211-preview.mp3" },
            { name: "N.Y. State of Mind", url: "https://assets.mixkit.co/active_storage/sfx/4212/4212-preview.mp3" },
            { name: "Juicy", url: "https://assets.mixkit.co/active_storage/sfx/4213/4213-preview.mp3" },
            { name: "Otis", url: "https://assets.mixkit.co/active_storage/sfx/4214/4214-preview.mp3" },
            { name: "Blunt Rolls", url: "https://assets.mixkit.co/active_storage/sfx/4215/4215-preview.mp3" },
            { name: "A Milli", url: "https://assets.mixkit.co/active_storage/sfx/4216/4216-preview.mp3" },
            { name: "Racks", url: "https://assets.mixkit.co/active_storage/sfx/4217/4217-preview.mp3" },
            { name: "Can't Tell Me Nothing", url: "https://assets.mixkit.co/active_storage/sfx/4218/4218-preview.mp3" },
            { name: "GOMD", url: "https://assets.mixkit.co/active_storage/sfx/4219/4219-preview.mp3" }
        ],
        electronic: [
            { name: "Around the World", url: "https://assets.mixkit.co/active_storage/sfx/4300/4300-preview.mp3" },
            { name: "One More Time", url: "https://assets.mixkit.co/active_storage/sfx/4301/4301-preview.mp3" },
            { name: "Kernkraft 400", url: "https://assets.mixkit.co/active_storage/sfx/4302/4302-preview.mp3" },
            { name: "Animals", url: "https://assets.mixkit.co/active_storage/sfx/4303/4303-preview.mp3" },
            { name: "Titanium", url: "https://assets.mixkit.co/active_storage/sfx/4304/4304-preview.mp3" },
            { name: "Levels", url: "https://assets.mixkit.co/active_storage/sfx/4305/4305-preview.mp3" },
            { name: "Clarity", url: "https://assets.mixkit.co/active_storage/sfx/4306/4306-preview.mp3" },
            { name: "Scary Monsters", url: "https://assets.mixkit.co/active_storage/sfx/4307/4307-preview.mp3" },
            { name: "Lean On", url: "https://assets.mixkit.co/active_storage/sfx/4308/4308-preview.mp3" },
            { name: "Where Are You", url: "https://assets.mixkit.co/active_storage/sfx/4309/4309-preview.mp3" },
            { name: "Don't Start Now", url: "https://assets.mixkit.co/active_storage/sfx/4310/4310-preview.mp3" },
            { name: "Your Body", url: "https://assets.mixkit.co/active_storage/sfx/4311/4311-preview.mp3" },
            { name: "Satisfaction", url: "https://assets.mixkit.co/active_storage/sfx/4312/4312-preview.mp3" },
            { name: "Wake Me Up", url: "https://assets.mixkit.co/active_storage/sfx/4313/4313-preview.mp3" },
            { name: "Hey Now", url: "https://assets.mixkit.co/active_storage/sfx/4314/4314-preview.mp3" },
            { name: "Clarity Remix", url: "https://assets.mixkit.co/active_storage/sfx/4315/4315-preview.mp3" },
            { name: "Bananza", url: "https://assets.mixkit.co/active_storage/sfx/4316/4316-preview.mp3" },
            { name: "Starlight", url: "https://assets.mixkit.co/active_storage/sfx/4317/4317-preview.mp3" },
            { name: "Electron", url: "https://assets.mixkit.co/active_storage/sfx/4318/4318-preview.mp3" },
            { name: "Neon", url: "https://assets.mixkit.co/active_storage/sfx/4319/4319-preview.mp3" }
        ],
        pop: [
            { name: "Candle in the Wind", url: "https://assets.mixkit.co/active_storage/sfx/4400/4400-preview.mp3" },
            { name: "Like a Virgin", url: "https://assets.mixkit.co/active_storage/sfx/4401/4401-preview.mp3" },
            { name: "Bad Romance", url: "https://assets.mixkit.co/active_storage/sfx/4402/4402-preview.mp3" },
            { name: "Toxic", url: "https://assets.mixkit.co/active_storage/sfx/4403/4403-preview.mp3" },
            { name: "Baby One More Time", url: "https://assets.mixkit.co/active_storage/sfx/4404/4404-preview.mp3" },
            { name: "I Wanna Dance", url: "https://assets.mixkit.co/active_storage/sfx/4405/4405-preview.mp3" },
            { name: "Shape of You", url: "https://assets.mixkit.co/active_storage/sfx/4406/4406-preview.mp3" },
            { name: "Perfect", url: "https://assets.mixkit.co/active_storage/sfx/4407/4407-preview.mp3" },
            { name: "Thinking Out Loud", url: "https://assets.mixkit.co/active_storage/sfx/4408/4408-preview.mp3" },
            { name: "Someone Like You", url: "https://assets.mixkit.co/active_storage/sfx/4409/4409-preview.mp3" },
            { name: "Rolling in the Deep", url: "https://assets.mixkit.co/active_storage/sfx/4410/4410-preview.mp3" },
            { name: "Poker Face", url: "https://assets.mixkit.co/active_storage/sfx/4411/4411-preview.mp3" },
            { name: "Just the Way", url: "https://assets.mixkit.co/active_storage/sfx/4412/4412-preview.mp3" },
            { name: "Uptown Funk", url: "https://assets.mixkit.co/active_storage/sfx/4413/4413-preview.mp3" },
            { name: "24K Magic", url: "https://assets.mixkit.co/active_storage/sfx/4414/4414-preview.mp3" },
            { name: "Blank Space", url: "https://assets.mixkit.co/active_storage/sfx/4415/4415-preview.mp3" },
            { name: "We Can't Stop", url: "https://assets.mixkit.co/active_storage/sfx/4416/4416-preview.mp3" },
            { name: "Love Story", url: "https://assets.mixkit.co/active_storage/sfx/4417/4417-preview.mp3" },
            { name: "Umbrella", url: "https://assets.mixkit.co/active_storage/sfx/4418/4418-preview.mp3" },
            { name: "Firework", url: "https://assets.mixkit.co/active_storage/sfx/4419/4419-preview.mp3" }
        ],
        chill: [
            { name: "Weightless", url: "https://assets.mixkit.co/active_storage/sfx/4500/4500-preview.mp3" },
            { name: "Mr. Brightside", url: "https://assets.mixkit.co/active_storage/sfx/4501/4501-preview.mp3" },
            { name: "Sundress", url: "https://assets.mixkit.co/active_storage/sfx/4502/4502-preview.mp3" },
            { name: "Golden Hour", url: "https://assets.mixkit.co/active_storage/sfx/4503/4503-preview.mp3" },
            { name: "Sunset", url: "https://assets.mixkit.co/active_storage/sfx/4504/4504-preview.mp3" },
            { name: "Ocean Avenue", url: "https://assets.mixkit.co/active_storage/sfx/4505/4505-preview.mp3" },
            { name: "Island in the Sun", url: "https://assets.mixkit.co/active_storage/sfx/4506/4506-preview.mp3" },
            { name: "Chasing Pavements", url: "https://assets.mixkit.co/active_storage/sfx/4507/4507-preview.mp3" },
            { name: "Hometown", url: "https://assets.mixkit.co/active_storage/sfx/4508/4508-preview.mp3" },
            { name: "Sunday Morning", url: "https://assets.mixkit.co/active_storage/sfx/4509/4509-preview.mp3" },
            { name: "Lazy Day", url: "https://assets.mixkit.co/active_storage/sfx/4510/4510-preview.mp3" },
            { name: "Peaceful Place", url: "https://assets.mixkit.co/active_storage/sfx/4511/4511-preview.mp3" },
            { name: "Tranquility", url: "https://assets.mixkit.co/active_storage/sfx/4512/4512-preview.mp3" },
            { name: "Sunrise", url: "https://assets.mixkit.co/active_storage/sfx/4513/4513-preview.mp3" },
            { name: "Waves", url: "https://assets.mixkit.co/active_storage/sfx/4514/4514-preview.mp3" },
            { name: "Breeze", url: "https://assets.mixkit.co/active_storage/sfx/4515/4515-preview.mp3" },
            { name: "Dreams", url: "https://assets.mixkit.co/active_storage/sfx/4516/4516-preview.mp3" },
            { name: "Nights", url: "https://assets.mixkit.co/active_storage/sfx/4517/4517-preview.mp3" },
            { name: "Nostalgia", url: "https://assets.mixkit.co/active_storage/sfx/4518/4518-preview.mp3" },
            { name: "Wanderlust", url: "https://assets.mixkit.co/active_storage/sfx/4519/4519-preview.mp3" }
        ]
    }
};

// Count total sounds
function getTotalSoundCount() {
    let count = 0;
    for (let section in soundsDatabase) {
        for (let category in soundsDatabase[section]) {
            count += soundsDatabase[section][category].length;
        }
    }
    return count;
}
